# Generated by Django 4.2.1 on 2023-09-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
