# Generated by Django 4.2.1 on 2023-06-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Name', max_length=200)),
                ('last_name', models.CharField(help_text='Surname', max_length=200)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Phone Number', max_length=19)),
                ('city', models.CharField(help_text='City', max_length=50)),
                ('address', models.CharField(help_text='Street, Building, etc', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Category of Furniture', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(help_text='Collection to that item belongs', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('code', models.CharField(max_length=8)),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('description', models.CharField(max_length=1000)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('attributes', models.CharField(choices=[('p', 'Produced'), ('s', 'Stopped')], help_text='state of production', max_length=2)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.furniturecategory')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.furniturecollection')),
            ],
        ),
    ]
