# Generated by Django 4.2.1 on 2023-06-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
