# Generated by Django 4.2.1 on 2023-09-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_furniture_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='static/images/mi_safe.png', null=True, upload_to=''),
        ),
    ]
