# Generated by Django 4.2.1 on 2023-06-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='Hiden', help_text='Surname', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='first_name',
            field=models.CharField(help_text='Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='last_name',
            field=models.CharField(help_text='Surname', max_length=200),
        ),
    ]
