# Generated by Django 4.2.1 on 2023-09-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_name_client_first_name_remove_clientuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='static/images/mi_safe.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='image',
            field=models.ImageField(default='static/images/mi_safe.png', null=True, upload_to=''),
        ),
    ]
